### ISSUE TITLE
UI/UX improvements for Node Operator Motions (add info to UI)

### ISSUE THREAD

**Issue by isidorosp** [lidofinance/easy-track-ui#35]
1) Could we please add the Node Operator name, for example:
![image](https://user-images.githubusercontent.com/27592/145799606-658da102-4ca4-45bd-9ce4-c5eb74d897c3.png)

https://github.com/lidofinance/easy-track-ui/blob/2b739ba28dcf0dd3ae45db56d389130dcf0f4c44/modules/motions/ui/MotionDescription/MotionDescription.tsx#L46

2) For Node Operators submitting motions, could we provide a drop-down list instead of requiring the node operator to input their ID manually? (I cannot mock the UI as I can't access the relevant form since I'm not a node operator). Or better yet, since the node operator needs to be logged in to access that form (and only NOs can raise limits for themselves), can we not infer the ID and just display that as hard-coded (i.e. the only editable field should be the desired key limit)?

**Comment by manneredboor** [comment]
Hi @isidorosp !
Thank you for this suggestions, we will take it for next release iteration.

**Comment by isidorosp** [comment]
Closed by #45 right?

**Comment by manneredboor** [comment]
@isidorosp with #44 exactly, by commits https://github.com/lidofinance/easy-track-ui/pull/44/commits/1dc626171a2bd6a18c572617f6c19d7e0362e151 and https://github.com/lidofinance/easy-track-ui/pull/44/commits/652aecb288a2c567fa1472d5522df9653434bd1e
