### ISSUE TITLE
More precise tx gas costs estimation

### ISSUE THREAD

**Issue by Psirex** [lidofinance/easy-track-ui#40]
The current implementation of gas strategy uses the hardcoded value for `gasLimit` which, sometimes leads to reverting transactions with `OUT_OF_GAS` reason (Example of reverted transaction: [0xb0caf4399effc6b7929624872aa0cd755872313d0d894d94af4b83eb4f001959](https://etherscan.io/tx/0xb0caf4399effc6b7929624872aa0cd755872313d0d894d94af4b83eb4f001959)).

To fix this problem and improve UX, it might be better to use ethers' [`estimateGas`](https://docs.ethers.io/v5/single-page/#/v5/api/contract/contract/-%23-contract-estimateGas) method for gas estimation. One of the additional features of such an approach is the ability to catch failing transactions before sending them.

As a temp solution, we can raise the default gas limit, but it's might still lead to reverted transactions for new types of motions.

**Comment by manneredboor** [comment]
https://github.com/lidofinance/easy-track-ui/pull/44/commits/99289d810e1f5a66907add5b09da89e94151ddaa
https://github.com/lidofinance/easy-track-ui/pull/44/commits/699e1d3672f90eb1a5d0c75b181a6284ad68e230
